### PR TITLE
5.0.0

### PR DESCRIPTION
**Pull request by jonathantneal**

### CODE REVIEW

**Comment by hacknug** [comment]
@jonathantneal should we merge this in and release a new version of the package? `postcss-normalize` seems to break because of one of the `.replace` we have here

**Comment by jonathantneal** [comment]
I didn’t know that. Yes, I think this is ready for release. Doing one more review of the whole codebase, first.

**Comment by hacknug** [comment]
Not sure if the issue is even related at all but since all tests are passing…

**Comment by jonathantneal** [comment]
I don’t know how to resolve this, but I noticed that removing [these lines from `test/postcss-tape.config.js`](https://github.com/csstools/postcss-tape/blob/ac829f1ef43c272e2323a4be673251f5455d71f9/test/postcss-tape.config.js#L34-L36) does not cause the test to fail.

```js
		warnings: {
			text: /should warn/
		},
```

**Comment by jonathantneal** [comment]
A fix is coming. Found more bugs.

**Comment by jonathantneal** [comment]
5.0.0 is published! :tada:

**Pull request merged**
